### PR TITLE
pages: new schedule, header sticks to top

### PR DESCRIPTION
**Pull request by matildepark**
He asked so nicely.

### CODE REVIEW

**Comment by jalehman** [comment]
@matildepark can you hook up the date toggle to query params so that the schedule is back button compatible?

**Comment by matildepark** [comment]
Can it be done Monday in a separate PR?

**Comment by jalehman** [comment]
Sure

**Comment by thomas-kroes** [comment]
Oke a few changes: 
Friday
Universe stage: 3:15 El Salvador DAO Law announcement by Stephen Galebach
3:30 %flappy-bird workshop

Saturday
Universe stage: 
1:00 How to Overthrow the Government using Vienna Hypertext
3:15 Long term lock out: renter economies in the smart home

Sunday
delete El Salvador Dao Law

**Comment by jalehman** [comment]
@gordoncc Joe had to drop, so that's why he's been removed.

**Pull request merged**
