### PR TITLE
added hero video and new colors

### PR DESCRIPTION
**Pull request by gordoncc**
new assets from other means.

looks like the navigation links are behaving oddly and don't quite make it to the right section point - not sure what's up there.

### CODE REVIEW

**Comment by matildepark** [comment]
This looks so nice! Do you mean that the hero video is overlapped by the navigation and isn't below it?

**Comment by matildepark** [comment]
Just remove `max-height: calc(100vh - 50px)` and it'll look normal. It's because it's sized to fit the page but it's also `object-fit: cover` so it's scaling the video up to fit the viewport. The aspect ratio isn't matching what you're giving it to scale into, so it's resizing the video and cutting the top off.

**Comment by matildepark** [comment]
> don't quite make it to the right section point

Oh I just understood what that meant

**Comment by matildepark** [comment]
It is making it to the right section — the divs are themselves marked with ids, and the divs have margins. If you want it to jump to the literal header, the headers need ids, not the div, but that will be kinda weird in its own way.

**Comment by gordoncc** [comment]
Oh you're right it's behaving correctly.  Must have gotten dizzy with all the moving imagery

**Pull request merged**
